### ISSUE TITLE
uv_mapped.obj does not exist

### ISSUE THREAD

**Issue by yankeesong** [yihua7/NeRF-Texture#6]
I got the following error when trying to reproduce the results:

Use xatlas UV mapping ...
Traceback (most recent call last):
  File "/media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/main.py", line 159, in <module>
    model = NeRFNetwork(
  File "/media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/nerf/network_curvedfield.py", line 130, in __init__
    self.meshfea_field = MeshFeatureField(hash=hash, mesh_path=surface_mesh_path, h_threshold=h_threshold, K=8, bound=bound, clustering=clustering, prob_model=prob_model, pred_normal=self.render_light_model, use_lip_mlp_for_normal=self.use_lip_mlp_for_normal, pattern_rate=pattern_rate, num_level=num_level, bound_output_normal=bound_output_normal)
  File "/media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/tools/map.py", line 600, in __init__
    self.meshprojector = MeshProjector(device=self.device, mesh_path=self.mesh_path, store_f=True, store_uv=True)
  File "/media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/tools/map.py", line 359, in __init__
    self.mesh.export('./test_data/uv_mapped.obj')
  File "/home/ryanrzzhang/anaconda3/envs/NeRF-Texture/lib/python3.10/site-packages/trimesh/base.py", line 2830, in export
    return export_mesh(
  File "/home/ryanrzzhang/anaconda3/envs/NeRF-Texture/lib/python3.10/site-packages/trimesh/exchange/export.py", line 60, in export_mesh
    file_obj = open(file_path, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/test_data/uv_mapped.obj'

Some help please?

**Comment by yihua7** [comment]
The log indicates that trimesh failed to export the mesh 'uv_mapped.obj' to the directory 'media/ryanrzzhang/CE4E3B8A4E3B6A7B/yankesong/NeRF-Texture/test_data/’. 
Does the path exist? Do you have the permission to write in?

**Comment by yankeesong** [comment]
Do I need to create a /test_data/ sub-directory? I wasn't indicated in the documentation.

**Comment by yihua7** [comment]
Yes, you need to create a ./test_data/ directory and the mesh can be exported.

**Comment by yankeesong** [comment]
Got it thanks! One further question: how much GPU memory is needed to run the program? Is there an easy way to allow multi-GPU if I run OOM on a single GPU?

**Comment by yihua7** [comment]
- The code will take up about 12G of GPU memory.
- I never ran the code on a multi-GPU setup, as a single 3090 was always enough for me. : )

**Comment by yankeesong** [comment]
Got it. Thanks!
